import '../models/shop_model.dart';
import '../models/product_model.dart';

class DemoData {
  static const String shopIdPrefix = 'demo_';

  static List<ShopModel> shops = [
    ShopModel(
      id: '${shopIdPrefix}1',
      ownerId: 'demo',
      nameEn: 'Urban Threads',
      nameAr: 'أوربان ثريدز',
      descEn: 'Modern streetwear and casual fashion for the urban lifestyle.',
      descAr: 'ملابس الشارع العصرية والكاجوال لنمط الحياة الحضري.',
      logoUrl: 'https://picsum.photos/seed/urban/200/200',
      coverUrl: 'https://picsum.photos/seed/urbancover/600/300',
      category: 'Modern',
      city: 'Amman',
      phone: '+962700000001',
      fulfillmentRate: 95.0,
      totalOrders: 340,
      successfulOrders: 323,
      isDemo: true,
    ),
    ShopModel(
      id: '${shopIdPrefix}2',
      ownerId: 'demo',
      nameEn: 'Desert Rose Boutique',
      nameAr: 'بوتيك وردة الصحراء',
      descEn: 'Elegant traditional wear with a modern twist.',
      descAr: 'ملابس تقليدية أنيقة بلمسة عصرية.',
      logoUrl: 'https://picsum.photos/seed/desertrose/200/200',
      coverUrl: 'https://picsum.photos/seed/desertcover/600/300',
      category: 'Traditional',
      city: 'Amman',
      phone: '+962700000002',
      fulfillmentRate: 88.0,
      totalOrders: 210,
      successfulOrders: 185,
      isDemo: true,
    ),
    ShopModel(
      id: '${shopIdPrefix}3',
      ownerId: 'demo',
      nameEn: 'SportFlex',
      nameAr: 'سبورت فليكس',
      descEn: 'High-performance sportswear and athletic gear.',
      descAr: 'ملابس رياضية عالية الأداء ومعدات رياضية.',
      logoUrl: 'https://picsum.photos/seed/sportflex/200/200',
      coverUrl: 'https://picsum.photos/seed/sportcover/600/300',
      category: 'Sportswear',
      city: 'Irbid',
      phone: '+962700000003',
      fulfillmentRate: 92.0,
      totalOrders: 156,
      successfulOrders: 144,
      isDemo: true,
    ),
    ShopModel(
      id: '${shopIdPrefix}4',
      ownerId: 'demo',
      nameEn: 'Tiny Tots Fashion',
      nameAr: 'أزياء الصغار',
      descEn: 'Cute and comfortable clothing for kids of all ages.',
      descAr: 'ملابس لطيفة ومريحة للأطفال من جميع الأعمار.',
      logoUrl: 'https://picsum.photos/seed/tinytots/200/200',
      coverUrl: 'https://picsum.photos/seed/totscover/600/300',
      category: 'Kids',
      city: 'Zarqa',
      phone: '+962700000004',
      fulfillmentRate: 78.0,
      totalOrders: 89,
      successfulOrders: 69,
      isDemo: true,
    ),
  ];

  static List<ProductModel> products = [
    // Urban Threads - 8 products
    ProductModel(
      id: '${shopIdPrefix}p1', shopId: '${shopIdPrefix}1',
      nameEn: 'Classic Denim Jacket', nameAr: 'جاكيت دينم كلاسيكي',
      descEn: 'Timeless denim jacket with a modern fit.', descAr: 'جاكيت دينم كلاسيكي بقصة عصرية.',
      price: 45.00, sizes: ['S', 'M', 'L', 'XL'], category: 'Modern',
      images: ['https://picsum.photos/seed/jacket1/400/500', 'https://picsum.photos/seed/jacket2/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p2', shopId: '${shopIdPrefix}1',
      nameEn: 'Slim Fit Chinos', nameAr: 'بنطلون شينو بقصة ضيقة',
      descEn: 'Comfortable chinos perfect for any occasion.', descAr: 'بنطلون شينو مريح مناسب لأي مناسبة.',
      price: 28.50, sizes: ['30', '32', '34', '36'], category: 'Modern',
      images: ['https://picsum.photos/seed/chinos1/400/500', 'https://picsum.photos/seed/chinos2/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p3', shopId: '${shopIdPrefix}1',
      nameEn: 'Graphic Tee', nameAr: 'تي شيرت مطبوع',
      descEn: 'Cotton t-shirt with unique graphic prints.', descAr: 'تي شيرت قطني بطباعات جرافيك فريدة.',
      price: 15.00, sizes: ['S', 'M', 'L', 'XL'], category: 'Modern',
      images: ['https://picsum.photos/seed/tee1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p4', shopId: '${shopIdPrefix}1',
      nameEn: 'Leather Bomber Jacket', nameAr: 'جاكيت بومبر جلدي',
      descEn: 'Premium leather bomber jacket.', descAr: 'جاكيت بومبر جلدي فاخر.',
      price: 85.00, sizes: ['M', 'L', 'XL'], category: 'Modern',
      images: ['https://picsum.photos/seed/bomber1/400/500', 'https://picsum.photos/seed/bomber2/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p5', shopId: '${shopIdPrefix}1',
      nameEn: 'Casual Hoodie', nameAr: 'هودي كاجوال',
      descEn: 'Warm and cozy hoodie for everyday wear.', descAr: 'هودي دافئ ومريح للاستخدام اليومي.',
      price: 32.00, sizes: ['S', 'M', 'L', 'XL', 'XXL'], category: 'Modern',
      images: ['https://picsum.photos/seed/hoodie1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p6', shopId: '${shopIdPrefix}1',
      nameEn: 'Cargo Pants', nameAr: 'بنطلون كارجو',
      descEn: 'Utility cargo pants with multiple pockets.', descAr: 'بنطلون كارجو عملي بجيوب متعددة.',
      price: 35.00, sizes: ['30', '32', '34', '36'], category: 'Modern',
      images: ['https://picsum.photos/seed/cargo1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p7', shopId: '${shopIdPrefix}1',
      nameEn: 'Oversized Knit Sweater', nameAr: 'كنزة صوف واسعة',
      descEn: 'Cozy oversized knit sweater for chilly days.', descAr: 'كنزة صوف واسعة ودافئة للأيام الباردة.',
      price: 40.00, sizes: ['S', 'M', 'L'], category: 'Modern',
      images: ['https://picsum.photos/seed/sweater1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p8', shopId: '${shopIdPrefix}1',
      nameEn: 'Slim Black Jeans', nameAr: 'جينز أسود بقصة ضيقة',
      descEn: 'Essential slim fit black jeans.', descAr: 'جينز أسود ضروري بقصة ضيقة.',
      price: 30.00, sizes: ['28', '30', '32', '34', '36'], category: 'Modern',
      images: ['https://picsum.photos/seed/jeans1/400/500'],
      isDemo: true,
    ),
    // Desert Rose Boutique - 7 products
    ProductModel(
      id: '${shopIdPrefix}p9', shopId: '${shopIdPrefix}2',
      nameEn: 'Embroidered Thobe', nameAr: 'ثوب مطرز',
      descEn: 'Hand-embroidered traditional thobe.', descAr: 'ثوب تقليدي مطرز يدوياً.',
      price: 65.00, sizes: ['S', 'M', 'L', 'XL'], category: 'Traditional',
      images: ['https://picsum.photos/seed/thobe1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p10', shopId: '${shopIdPrefix}2',
      nameEn: 'Silk Abaya', nameAr: 'عباية حرير',
      descEn: 'Luxurious silk abaya with delicate details.', descAr: 'عباية حرير فاخرة بتفاصيل دقيقة.',
      price: 120.00, sizes: ['One Size'], category: 'Traditional',
      images: ['https://picsum.photos/seed/abaya1/400/500', 'https://picsum.photos/seed/abaya2/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p11', shopId: '${shopIdPrefix}2',
      nameEn: 'Pashmina Shawl', nameAr: 'شال بشمين',
      descEn: 'Soft pashmina shawl in elegant colors.', descAr: 'شال بشمين ناعم بألوان أنيقة.',
      price: 25.00, sizes: ['One Size'], category: 'Traditional',
      images: ['https://picsum.photos/seed/shawl1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p12', shopId: '${shopIdPrefix}2',
      nameEn: 'Beaded Evening Dress', nameAr: 'فستان سهرة بالخرز',
      descEn: 'Stunning beaded evening dress.', descAr: 'فستان سهرة مذهل مزين بالخرز.',
      price: 95.00, sizes: ['S', 'M', 'L'], category: 'Traditional',
      images: ['https://picsum.photos/seed/dress1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p13', shopId: '${shopIdPrefix}2',
      nameEn: 'Traditional Kaftan', nameAr: 'قفطان تقليدي',
      descEn: 'Beautiful kaftan with gold embroidery.', descAr: 'قفطان جميل بتطريز ذهبي.',
      price: 75.00, sizes: ['M', 'L', 'XL'], category: 'Traditional',
      images: ['https://picsum.photos/seed/kaftan1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p14', shopId: '${shopIdPrefix}2',
      nameEn: 'Velvet Hijab Set', nameAr: 'طقم حجاب مخمل',
      descEn: 'Luxurious velvet hijab with matching underscarf.', descAr: 'حجاب مخمل فاخر مع واقية مطابقة.',
      price: 22.00, sizes: ['One Size'], category: 'Traditional',
      images: ['https://picsum.photos/seed/hijab1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p15', shopId: '${shopIdPrefix}2',
      nameEn: 'Gold Bracelet Set', nameAr: 'طقم أساور ذهبية',
      descEn: 'Elegant gold-plated bracelet set.', descAr: 'طقم أساور مطلية بالذهب أنيقة.',
      price: 35.00, sizes: ['One Size'], category: 'Accessories',
      images: ['https://picsum.photos/seed/bracelet1/400/500'],
      isDemo: true,
    ),
    // SportFlex - 7 products
    ProductModel(
      id: '${shopIdPrefix}p16', shopId: '${shopIdPrefix}3',
      nameEn: 'Compression T-Shirt', nameAr: 'تي شيرت ضاغط',
      descEn: 'Moisture-wicking compression tee for workouts.', descAr: 'تي شيرت ضاغط لامتصاص العرق للتمارين.',
      price: 20.00, sizes: ['S', 'M', 'L', 'XL'], category: 'Sportswear',
      images: ['https://picsum.photos/seed/compression1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p17', shopId: '${shopIdPrefix}3',
      nameEn: 'Running Shorts', nameAr: 'شورت جري',
      descEn: 'Lightweight running shorts with built-in liner.', descAr: 'شورت جري خفيف مع بطانة داخلية.',
      price: 18.00, sizes: ['S', 'M', 'L', 'XL'], category: 'Sportswear',
      images: ['https://picsum.photos/seed/shorts1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p18', shopId: '${shopIdPrefix}3',
      nameEn: 'Sports Bra', nameAr: 'حمالة رياضية',
      descEn: 'High-support sports bra for intense workouts.', descAr: 'حمالة رياضية عالية الدعم للتمارين المكثفة.',
      price: 25.00, sizes: ['S', 'M', 'L', 'XL'], category: 'Sportswear',
      images: ['https://picsum.photos/seed/sportsbra1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p19', shopId: '${shopIdPrefix}3',
      nameEn: 'Track Pants', nameAr: 'بنطلون رياضي',
      descEn: 'Comfortable track pants with zippered pockets.', descAr: 'بنطلون رياضي مريح بجيوب بسحاب.',
      price: 30.00, sizes: ['S', 'M', 'L', 'XL'], category: 'Sportswear',
      images: ['https://picsum.photos/seed/trackpants1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p20', shopId: '${shopIdPrefix}3',
      nameEn: 'Windbreaker Jacket', nameAr: 'جاكيت واقٍ من الرياح',
      descEn: 'Lightweight windbreaker for outdoor runs.', descAr: 'جاكيت خفيف واقٍ من الرياح للجري في الهواء الطلق.',
      price: 45.00, sizes: ['M', 'L', 'XL'], category: 'Sportswear',
      images: ['https://picsum.photos/seed/windbreaker1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p21', shopId: '${shopIdPrefix}3',
      nameEn: 'Yoga Leggings', nameAr: 'بنطلون يوجا',
      descEn: 'Stretchy high-waist yoga leggings.', descAr: 'بنطلون يوجا مطاطي عالي الخصر.',
      price: 28.00, sizes: ['XS', 'S', 'M', 'L'], category: 'Sportswear',
      images: ['https://picsum.photos/seed/yogapants1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p22', shopId: '${shopIdPrefix}3',
      nameEn: 'Athletic Socks (3 Pack)', nameAr: 'جوارب رياضية (3 أزواج)',
      descEn: 'Cushioned athletic socks for training.', descAr: 'جوارب رياضية مبطنة للتدريب.',
      price: 12.00, sizes: ['S', 'M', 'L'], category: 'Sportswear',
      images: ['https://picsum.photos/seed/socks1/400/500'],
      isDemo: true,
    ),
    // Tiny Tots Fashion - 6 products
    ProductModel(
      id: '${shopIdPrefix}p23', shopId: '${shopIdPrefix}4',
      nameEn: 'Kids Animal Hoodie', nameAr: 'هودي حيوانات للأطفال',
      descEn: 'Fun animal-themed hoodie for toddlers.', descAr: 'هودي مرح بتصميم حيوانات للأطفال الصغار.',
      price: 18.00, sizes: ['2T', '3T', '4T', '5'], category: 'Kids',
      images: ['https://picsum.photos/seed/kidshoodie1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p24', shopId: '${shopIdPrefix}4',
      nameEn: 'Denim Overalls', nameAr: 'أوفرول جينز',
      descEn: 'Cute denim overalls with adjustable straps.', descAr: 'أوفرول جينز لطيف بأشرطة قابلة للتعديل.',
      price: 25.00, sizes: ['2T', '3T', '4T', '5', '6'], category: 'Kids',
      images: ['https://picsum.photos/seed/overalls1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p25', shopId: '${shopIdPrefix}4',
      nameEn: 'Printed Leggings Set', nameAr: 'طقم بنطلون مطبوع',
      descEn: 'Colorful printed leggings with matching top.', descAr: 'بنطلون مطبوع ملون مع قميص مطابق.',
      price: 15.00, sizes: ['2T', '3T', '4T', '5'], category: 'Kids',
      images: ['https://picsum.photos/seed/leggingset1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p26', shopId: '${shopIdPrefix}4',
      nameEn: 'Winter Coat', nameAr: 'معطف شتوي',
      descEn: 'Warm winter coat with faux fur hood.', descAr: 'معطف شتوي دافئ بقلنسوة فرو صناعي.',
      price: 38.00, sizes: ['3T', '4T', '5', '6', '7'], category: 'Kids',
      images: ['https://picsum.photos/seed/kidscoat1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p27', shopId: '${shopIdPrefix}4',
      nameEn: 'Cotton Pajama Set', nameAr: 'طقم بيجاما قطني',
      descEn: 'Soft cotton pajama set with fun prints.', descAr: 'طقم بيجاما قطني ناعم برسومات مرحة.',
      price: 20.00, sizes: ['2T', '3T', '4T', '5', '6'], category: 'Kids',
      images: ['https://picsum.photos/seed/pajama1/400/500'],
      isDemo: true,
    ),
    ProductModel(
      id: '${shopIdPrefix}p28', shopId: '${shopIdPrefix}4',
      nameEn: 'School Uniform Shirt', nameAr: 'قميص مدرسي',
      descEn: 'Neat and comfortable school uniform shirt.', descAr: 'قميص مدرسي أنيق ومريح.',
      price: 14.00, sizes: ['4', '5', '6', '7', '8'], category: 'Kids',
      images: ['https://picsum.photos/seed/schoolshirt1/400/500'],
      isDemo: true,
    ),
  ];
}
